# Generated by Django 5.1.2 on 2024-10-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='roll',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
